name: MobileOne
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+32

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.5.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.15
  # Add the dependencies for any other Firebase products you want to use in your app
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  firebase: 7.3.0
  cloud_firestore: ^0.14.0+2
  uuid: ^2.1.0
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.4
  http: ^0.12.1
  fluttertoast: ^4.0.0
  firebase_crashlytics: ^0.1.3+3
  get_it: ^4.0.2
  shared_preferences: ^0.5.7+3
  permission_handler: ^4.0.0
  contacts_service: ^0.4.6
  barcode_scan: ^3.0.1
  json_annotation: ^3.0.1
  barcode: ^1.13.0
  barcode_widget: ^1.4.0
  image_picker: ^0.6.5
  gallery_saver: ^2.0.1
  flutter_svg: ^0.18.0
  firebase_storage: ^4.0.0
  flutter_animation_progress_bar: ^1.0.0
  speech_to_text: ^2.4.1
  flutter_material_color_picker: ^1.0.5
  flutter_email_sender: ^3.0.1
  flutter_local_notifications: ^1.4.4+4
  firebase_messaging: ^7.0.0
  pull_to_refresh: ^1.6.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_launcher_icons: "^0.7.3"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  android: true
  ios: true
  image_path_android: "android/app/src/main/res/drawable/circle_logo.xml"
  image_path_ios: "ios/Runner/Assets.xcassets/Contents.json"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/lang/en.json
    - resources/lang/fr.json
    - resources/messaging/cloud_messaging.json
    - assets/images/
    - pubspec.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
