/// Flutter icons QrCode
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QrCode
///      fonts:
///       - asset: fonts/QrCode.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class QrCode {
  QrCode._();

  static const _kFontFam = 'QrCode';
  static const _kFontPkg = null;

  static const IconData qrcode =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
