on:
  pull_request:
    branches:
      - '*'

name: Build Android
jobs:
  build:
    name: Build Android apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: fetch firebase config
        env:
          FIREBASE_CONFIG: ${{ secrets.ANDROID_GOOGLE_SERVICES }}
        run: |
          echo $FIREBASE_CONFIG > ./android/app/google-services.json
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --debug
